# Use via: go.amp.dev/ads
# Add new entries in alphabetical order
/ads: /about/ads
/amp-pwa-amp: https://blog.amp.dev/2018/06/19/the-shadow-reader-improved/
/auto-sw: https://github.com/ampproject/amp-sw/
/camp-code: https://github.com/ampproject/samples/tree/master/amp-camp
/cors: /documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests
/docs: /documentation/guides-and-tutorials/
/email: /about/email
/email-tools: /documentation/tools
/governance: /community/governance
/io-email: /documentation/examples/interactivity-dynamic-content/conference_survey_email/
/learn: /documentation/courses/
/optimize-amp: https://blog.amp.dev/2018/10/08/how-to-make-amp-even-faster/
/publishing-checklist: /documentation/guides-and-tutorials/optimize-and-measure/publishing_checklist
/samples: /documentation/examples/
/shopify-apps: https://blog.amp.dev/2019/04/15/shopify-apps-make-amp-easy-and-effective-for-ecommerce
/stories-best-practices: /documentation/guides-and-tutorials/develop/amp_story_best_practices
/stories: /about/stories
/sxg: /documentation/guides-and-tutorials/optimize-and-measure/signed-exchange
/templates: /documentation/templates/
/tools: /documentation/tools
/vision-mission: /about/mission-and-vision
/websites: /about/websites

# Regex-based entries
^/c/amp-([a-z-]+)$:
  url: /documentation/components/amp-$1
  useRegex: true
^/e/amp-([a-z-]+)$:
  url: /documentation/examples/components/amp-$1/
  useRegex: true
