---
name: 'Check: Grow link integrity'

on:
  push:
    paths:
      - 'pages/content/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing Node.js packages
        run: npm install

      - name: Checking grow link integrity
        run: |
          gulp buildSamples
          gulp importAll
          gulp lintGrow
