---
name: 'Lint: YAML'

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '!.github/**/*.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing Node.js packages
        run: npm install

      - name: Linting YAML files
        run: |
          gulp lintYaml
