---
name: 'Test: Playground'

on:
  push:
    paths:
      - 'package.json'
      - 'playground/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: Installing Node.js packages
        run: npm ci

      - name: Running Playground tests
        run: |
          npx gulp updateTestResources
          npm run test:playground -- --colors
