---
name: 'Test: Platform'

on:
  push:
    paths:
      - 'package.json'
      - 'platform/lib/**'
  pull_request:
    paths:
      - 'package.json'
      - 'platform/lib/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing Node.js packages
        run: npm install

      - name: Running Platform tests
        run: |
          gulp updateTestResources
          gulp buildComponentVersions
          npm run test:platform -- --colors
