---
name: 'Test: Pixi'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing Node.js packages
        run: npm install

      - name: Running Pixi tests
        run: |
          gulp updateTestResources
          gulp buildPixiFunctions
          npm run test:pixi -- --colors
